### ISSUE TITLE
license update and error in Analysis.py #L119 

### ISSUE THREAD

**Issue by MMathisLab** [CMGreenspon/NCams#2]
on line https://github.com/CMGreenspon/NCams/blob/9a308e3069c0852cb6f2eab25dd59ddf7816a7b0/Examples/Analysis.py#L119 

this should be deeplabcut.extract_outlier_frames(... 

Also, since you have included our code in your repo, you must adhere to our license, namely and copy of the code must be released under the same license, https://github.com/AlexEMG/DeepLabCut/blob/master/LICENSE

**Comment by nishbo** [comment]
Hi,

That line is as intended, the aim was only to add additional frames to the training data, refining outlier frames did not yield as good results as labeling more from our preliminary results. The DLC-related code is currently very loose and will be provided with much more documentation when we finalize the SOP for labeling frames.

As for the license, we do not actually have your code in our repo or any modifications of it, we are only calling the interface functions and using a configuration file, which may be released under a different license as derivative or linked work under LGPL, see also [A Work that Uses the Library description](https://copyleft.org/guide/comprehensive-gpl-guidech11.html#x14-10400010.4). For the files importing deeplabcut, as described in point 4 of the License, I have included the LGPL and GPL license files in the repository, as well as adding descriptive headers within the files: 9eacb61e1eb55a5f09e480959815ce45a150920e. Please tell me if that resolves the issue.

**Comment by MMathisLab** [comment]
Thanks for adding the headers. Perhaps while I have you: 

- you’re readme links are nearly all broken. - - You might also consider modifying tips, as how you describe adding new videos is not standard practice. You simply need to all new video by using the function add_new_videos not manually adding them to config.yaml.

**Comment by nishbo** [comment]
Thank you!

**Comment by MMathisLab** [comment]
You’re welcome. Glad you’re found our package useful!
