### ISSUE TITLE
 can you resend the original data and image

### ISSUE THREAD

**Issue by lishuaifu** [CMGreenspon/NCams#6]
Hello, can you resend the original data and image? The link has expired, thank you

**Comment by nishbo** [comment]
Hi, thank you for noticing it, the links might have expired or got deleted, I've updated the repository:
The example [raw data](https://uchicago.box.com/s/x6v8h67qt1de01dbvhy6uriuscavk1nr) and [raw images](https://uchicago.box.com/s/ot4q2huebbxalmb2opav4km4pbz6n49w) are uploading right now, should be uploaded within a day.

**Comment by lishuaifu** [comment]
thank you
